name: prf
description: "Easily save and load values locally. Effortless local persistence with type safety and zero boilerplate. Just get, set, and go. Drop-in replacement for raw SharedPreferences."
version: 2.4.5
homepage: https://github.com/jozzdart/prf
repository: https://github.com/jozzdart/prf
issue_tracker: https://github.com/jozzdart/prf/issues
topics:
  - shared-preferences
  - storage
  - state
  - persistence
  - local-storage

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.1
  synchronized: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
