name: prf
description: "Easily save and load values locally. Effortless local persistence with type safety and zero boilerplate. Just get, set, and go. Designed to fully replace raw use of SharedPreferences"
version: 2.1.0
homepage: https://github.com/jozzzzep/prf
repository: https://github.com/jozzzzep/prf
issue_tracker: https://github.com/jozzzzep/prf/issues
topics:
  - shared-preferences
  - storage
  - state
  - persistence
  - flutter

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
